spring:
  application:
    name: notification-manager
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: notification_manager
  cloud:
    function:
      definition: messageMentioned;messageReacted;newFriendRequest;userRegistrationUpstreamConsumer
    Stream:
      bindings:
        messageMentioned-in-0:
          destination: topic.message.mentioned
        messageReacted-in-0:
          destination: topic.message.reacted
        newFriendRequest-in-0:
          destination: topic.user.new-friend
        userRegistrationUpstreamConsumer-in-0:
          destination: topic.user.registration
        newFriendRequest-out-0:
          destination: topic.notification.events
        messageReacted-out-0:
          destination: topic.notification.events
        messageMentioned-out-0:
          destination: topic.notification.events
      kafka:
        binder:
          brokers: localhost:9092
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
