spring:
  application:
    name: notification-manager
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: notification_manager
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
