spring:
  application:
    name: notification-manager
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: notification_manager
  cloud:
    function:
      definition: userRegistrationUpstreamConsumer; handleMessageMentionedEvent; handleMessageReactedEvent; handleNewFriendRequestEvent; handleFriendRequestAcceptedEvent; handleConversationEvent
    stream:
      # messsage events, conversation events
      bindings:
        userRegistrationUpstreamConsumer-in-0:
          destination: topic.user.registration
        handleConversationEvent-in-0:
          destination: topic.conversation.events
        handleMessageMentionedEvent-in-0:
          destination: topic.notification.trigger.message.mentioned
        handleMessageReactedEvent-in-0:
          destination: topic.notification.trigger.message.reacted
        handleNewFriendRequestEvent-in-0:
          destination: topic.notification.trigger.friend.request.new
        handleFriendRequestAcceptedEvent-in-0:
          destination: topic.notification.trigger.friend.request.accepted
        handleMessageMentionedEvent-out-0:
          destination: topic.notification.events
        handleMessageReactedEvent-out-0:
          destination: topic.notification.events
        handleNewFriendRequestEvent-out-0:
          destination: topic.notification.events
        handleFriendRequestAcceptedEvent-out-0:
          destination: topic.notification.events
      kafka:
        binder:
          brokers: localhost:9092
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
