package com.chat.notification_manager.enums;

public enum NotificationType {
  NOTIFICATION_MESSAGE_REACTED,
  NOTIFICATION_MESSAGE_MENTIONED,
  NOTIFICATION_NEW_FRIEND_REQUEST,
  NOTIFICATION_FRIEND_REQUEST_ACCEPTED
}
